version: "3"
services:
  event_back:
    container_name: event_back
    build:
      context: ./event_back
      dockerfile: Dockerfile
    working_dir: "/usr/event_back"
    volumes:
      - ../event_back:/usr/event_back
    environment:
      TZ: Asia/Tokyo
    networks:
      - event-network
    # restart: always
    ports:
      - 8002:8084
  nginx_event:
    image: nginx
    container_name: nginx_event
    environment:
      TZ: Asia/Tokyo
      FASTAPI: event_back
    networks:
      - event-network
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ../nginx/templates
        target: /etc/nginx/templates
      - type: bind
        source: ../../frontend/event_front/dist
        target: /usr/share/nginx/html
networks:
  event-network:
    external: true
